version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./scripts/postgres/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rchauhan9102@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Admin@123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  web:
    depends_on:
      - db
    image: tomcat:9.0
    volumes:
      - ./target/ShoppingCart.war:/usr/local/tomcat/webapps/ShoppingCart.war
    ports:
      - '8082:8080'
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres?currentSchema=shopping_cart
      DB_USER: postgres
      DB_PASSWORD: postgres
volumes:
  local_pgdata:
  pgadmin-data: